name: TagBot
on:
  issue_comment:
    types:
      - created
  schedule:
    - cron: */5 * * * *
  workflow_dispatch:
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: cat $GITHUB_EVENT_PATH | python -m json.tool
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
