name: TagBot
on:
  push:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: FOOBAR
    steps:
      - run: echo $GITHUB_TOKEN
      - run: echo AHHHHHH
        if: github.event_name == 'schedule'
      - run: env
      - run: cat $GITHUB_EVENT_PATH | python -m json.tool
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
